In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [65]:
states = np.array([[0,0,0,0],
                   [0,0,0,1],
                   [0,0,1,0],
                   [0,0,1,1],
                   [0,1,0,0],
                   [0,1,0,1],
                   [0,1,1,0],
                   [0,1,1,1],
                   [1,0,0,0],
                   [1,0,0,1],
                   [1,0,1,0],
                   [1,0,1,1],
                   [1,1,0,0],
                   [1,1,0,1],
                   [1,1,1,0],
                   [1,1,1,1]])

# Adding new something
c = 0

num_states = states.shape[0]

actions = np.array([[0,0,0,0],
                    [1,0,0,0],
                    [0,1,0,0],
                    [0,0,1,0],
                    [0,0,0,1]])

num_actions = actions.shape[0]

connectivity_matrix = \
    np.array([[0,0,-1,0],
              [1,0,-1,-1],
              [0,1,0,0],
              [-1,1,1,0],])

cm_s = np.dot(connectivity_matrix, states[num_states-1])
cm_s[cm_s < 0] = 0
print(cm_s)
for j in range(num_actions):
    cms_a = np.bitwise_xor(cm_s, actions[j])
    print(cms_a)


# for i in range(num_states):
#     cm_s = np.dot(connectivity_matrix, states[i])
#     # print(cm_s)
#     for j in range(num_actions):
#         cms_a = np.bitwise_xor(cm_s, actions[j])
        # print(cms_a)


# Calculate the reward for a given state and action
def getReward(state_index,action_index):
    if action_index != 0:
        return np.sum(states[state_index]*5)-1
    else:
        return np.sum(states[state_index]*5)


# Calculate the noise for a given probability
def getNoise(prob):
    return np.random.binomial(n=1,p=prob,size=4)



[0 0 1 1]
[0 0 1 1]
[1 0 1 1]
[0 1 1 1]
[0 0 0 1]
[0 0 1 0]


19

### Part a

In [ ]:
prob = 0.05
theta = 0.01

vs0 = np.zeros(num_states)

noise = getNoise(prob)

### Part b

### Part c