In [1]:
import numpy as np

In [17]:
# Variables
gamma = 0.9
num_states = 2

# Transition probabilities
p_a1 = np.array([[0.2 , 0.8],
                 [ 0  ,  1 ]])
p_a2 = np.array([[ 1  , 0  ],
                 [0.1 ,0.9 ]])
psa = np.array([p_a1, p_a2])

# Reward for each state-action pair
rss_a1 = np.array([[-1.5  , 0.5],
                 [-1.5  , 0.5]])
rss_a2 = np.array([[-1    , 1  ],
                 [-1    , 1  ]])
rsa = np.array([rss_a1, rss_a2])


# Calculate the reward for each action
# Each index of the result is the reward for the corresponding state
r_a1 = np.dot(np.multiply(p_a1, rss_a1),np.ones((num_states,1)))
r_a2 = np.dot(np.multiply(p_a2, rss_a2),np.ones((num_states,1)))


init_pi = np.array([1, 0]).astype(int)

v = np.array([4.51,5])

# print(0.9*np.dot(p_a1,v))
# print(0.9*np.dot(p_a2,v))

def policy_evaluation(p, r, pi, v, gamma):
    return np.identity(num_states) - gamma * np.dot(p[pi], np.ones((2,1)))



[1 0]


[[ 0.  1.  4.]
 [ 9. 16. 25.]
 [36. 49. 64.]]
